# Generated by Django 3.2 on 2022-06-27 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-received_date']},
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='accepted_date',
        ),
        migrations.AddField(
            model_name='contactform',
            name='received_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
