# Generated by Django 3.2 on 2022-06-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_contactform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed')], default=0),
        ),
    ]
