# Generated by Django 3.2 on 2022-06-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_contactform_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
