# Generated by Django 3.2 on 2022-06-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_rename_contactform_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactForm',
        ),
    ]
