# Generated by Django 3.2 on 2022-06-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20220630_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Contacted'), (2, 'Accepted'), (3, 'Canceled')], default=0),
        ),
    ]
